(defun fload (filename)
  (let* ((dot-string (make-string (cl:- 40 (cl:+ 3 (length filename)))
                                  :initial-element #\.)))
    (format t "Loading ~a ..." filename)
    (load filename)
    (format t "~a OK~%" dot-string)))
(fload "src/gagm.lisp")
(fload "src/package.lisp")
(fload "src/generic-functions.lisp")
(fload "src/utilities.lisp")
(fload "src/macros.lisp")
(fload "src/reader-macros.lisp")
(fload "src/infix-to-prefix.lisp")
(fload "src/ast-nodes.lisp")
(fload "src/basic-language.lisp")
(fload "src/code-generation-utils.lisp")
(fload "src/problem-examples.lisp")
(fload "src/writer-gmpl.lisp")
(fload "src/lmml-case-sensitivity.lisp")
