(defun fload (filename)
    (let* ((dot-string (make-string (cl:- 50 (cl:+ 3 (length filename)))
			  :initial-element #\.)))
    (format t "Loading ~a ..." filename)
    (load filename)
    (format t "~a OK~%" dot-string)))

 (format t "Files form lmml: ~%")
(fload "lmml/src/gagm.lisp")
(fload "lmml/src/package.lisp")
(fload "lmml/src/generic-functions.lisp")
(fload "lmml/src/utilities.lisp")
(fload "lmml/src/macros.lisp")
(fload "lmml/src/reader-macros.lisp")
(fload "lmml/src/infix-to-prefix.lisp")
(fload "lmml/src/ast-nodes.lisp")
(fload "lmml/src/basic-language.lisp")
(fload "lmml/src/code-generation-utils.lisp")
(fload "lmml/src/problem-examples.lisp")
(fload "lmml/src/writer-gmpl.lisp")
(fload "lmml/src/lmml-case-sensitivity.lisp")
(format t "~%Files from src~%")
(fload  "./src/vrp-function-generator.lisp")

(format t "~%Package VRP~%")
(fload  "./src/vrp-package.lisp")

(format t "~%Files form utils: ~%")
(fload "./utils/vrp-random-number-generation.lisp")
(fload "./utils/vrp-utils.lisp")

(format t "~%Files form src~%")
(fload  "./src/vrp-utils.lisp")
(fload  "./src/vrp-characteristics.lisp")
(fload  "./src/vrp-description-definition.lisp")
(fload  "./src/vrp-prerequisites.lisp")
(fload  "./src/vrp-problem-solution-pair.lisp")
(fload  "./src/vrp-high-level-strategy.lisp")
(fload  "./src/vrp-generate-solution.lisp")
(fload  "./src/vrp-variables-parameters.lisp")
(fload  "./src/vrp-from-high-to-low.lisp")
(fload  "./src/vrp-model-evaluator.lisp")
(fload  "./src/vrp-meaning-restrictions.lisp")

(format t "~%Package AV-VRP~%")
(fload  "./src/av-vrp-package.lisp")
